name: Build deploy Page PROD

on:
  workflow_dispatch:
    inputs:
      manual_deploy:
        description: "Manual Deploy"
        required: true
        type: boolean
        default: true
  push:
    branches:
      - main

env:
  IMAGE: reset-password
  PORT: 3000
  REGION: us-east1
  CPU: 2
  MEMORY: 128Mi
  TIMEOUT: 300
  CONCURRENCY: 80
  MAX_INSTANCES: 1
  MIN_INSTANCES: 0

jobs:
  deploy:
    name: Deploy Page
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Use gcloud CLI
      run: gcloud info

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Docker configuration
      run: |-
        gcloud auth configure-docker \
        us-east1-docker.pkg.dev

    - name: Build
      run: |-
        docker build \
          --tag "us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ar-backend/${{ env.IMAGE }}-prod:latest" \
          ./reset_password

    - name: Publish
      run: |-
        docker push "us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ar-backend/${{ env.IMAGE }}-prod:latest"

    - name: Deploy
      run: |
        gcloud run deploy run-${{ env.IMAGE }}-prod \
        --image us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ar-backend/${{ env.IMAGE }}-prod:latest \
        --platform managed \
        --allow-unauthenticated \
        --cpu=$CPU \
        --port=$PORT \
        --memory=$MEMORY \
        --region $REGION \
        --timeout=$TIMEOUT \
        --concurrency=$CONCURRENCY \
        --min-instances=$MIN_INSTANCES \
        --max-instances=$MAX_INSTANCES 